### ISSUE TITLE
Where can i download HetrixToolsAgent.exe?

### ISSUE THREAD

**Issue by astutesoftware** [hetrixtools/agent-win#4]
Could not find any reference to download on this plage.
https://github.com/hetrixtools/agent-win/releases/tag/v1.5.4-alpha

**Comment by hetrixtools** [comment]
Hello,

Please follow these steps to locate the .exe file download link:
- go on the 'Release' page: https://github.com/hetrixtools/agent-win/releases
- locate the 'Assets' link, towards the bottom of every release version
- clicking on the 'Assets' link will expand the release assets, where you can find and click on: 'HetrixToolsAgent.exe'

Hopefully this helps.
